### DISCUSSION TITLE
Bastion support for private instances

### DISCUSSION THREAD

**Discussion by arindam-bandyopadhyay** [oracle/cluster-api-provider-oci#43] [Ideas]
**Problem Description**

CAPOCI by default creates Kubernetes master and worker nodes as private, i.e they don't have any public ip, only they have private ip. As a result, the operators manually needs to create bastions hosts(a compute with publci ip) aka jump host or use bastion service(https://www.oracle.com/security/cloud-security/bastion) to connect to those private instances.

**Solution**

CAPOCI should automatically create bastion service(https://docs.oracle.com/en-us/iaas/Content/Bastion/Concepts/bastionoverview.htm) in the control-plan (kubernetes master) instance subnet and worker node subnet if user opt for it via oci cluster spec. This would be allowed only for `control-plan` subnet and `worker` subnet role.
Example:
```yaml
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OCICluster
metadata:
  name: foo
spec:
  networkSpec:
    vcn:
      name: cluster-vcn
      subnets:
        - name: cp-subnet
          role: control-plan
          type: private
          bastion:
            name: control-plan-bastion
            cidr: 11.0.0.0/24
        - name: worker-subnet
          role: worker
          type: private
          bastion:
            name: worker-bastion
            cidr: 10.0.0.0/24
```
Notes
- This bastion spec is optional. CAPOCI won't create any default bastion if inside subnet, bastian spec is missing
- `name` is the name of the bastion and `cidr` is the allowed cidr that would have access to the private instance via bastion service
- CAPOCI would only create the bastion on the subnet. However, it won't create the bastion sessions since bastion sessions are short-lived (TTL 180 minutes). The user(operator) needs to create bastion session manually when they want to connect to the instance
- We would document how to create bastion sessions.
